.PHONY: help catalog-check catalog-pins docs-sync docs-sync-offline docs-build docs-check docs-serve docs-clean

.DEFAULT_GOAL := help

CYAN   := \033[0;36m
YELLOW := \033[0;33m
NC     := \033[0m

# Passed into docker-compose.yml so files written to the bind mount keep the
# invoking user's ownership. MKDOCS_IMAGE is the same tag the sibling sites pin.
export DOCKER_UID := $(shell id -u)
export DOCKER_GID := $(shell id -g)
export MKDOCS_IMAGE ?= squidfunk/mkdocs-material:9.7.6
# php-coding-plugin is private. Unauthenticated raw GitHub 404s its README.
# A local `gh auth token` is enough. CI supplies the DOCS_SYNC_TOKEN secret
# as GH_TOKEN; `?=` leaves that value alone when it is already set.
export GH_TOKEN ?= $(shell gh auth token 2>/dev/null)

COMPOSE     ?= docker compose
DOCS_BUILD  := site
FETCHED     := .fetched
# -T: no TTY, so CI and `make docs-check` do not wait on one.
COMPOSE_RUN := $(COMPOSE) run --rm --no-deps -T

# Destinations of sources.json `theme.files`. Regenerated by `make docs-sync`.
# scripts/check_brand_paths.py compares this list to sources.json and .gitignore.
THEME_FETCHED := \
	pages/stylesheets/tokens.css \
	pages/stylesheets/material.css \
	pages/stylesheets/landing.css \
	overrides/home.html \
	overrides/partials/copyright.html \
	pages/assets/cadasto-mark.png

help: ## Display this help message
	@echo ""
	@awk 'BEGIN {FS = ":.*##"; printf "Usage:\n  make $(CYAN)<target>$(NC)\n\n"} \
	  /^[a-zA-Z_0-9-]+:.*?##/ { printf "  $(CYAN)%-18s$(NC) %s\n", $$1, $$2 } \
	  /^##@/ { printf "\n$(YELLOW)%s$(NC)\n", substr($$0, 5) }' $(MAKEFILE_LIST)
	@echo ""

##@ Catalog

catalog-check: ## Validate the marketplace manifests
	python3 scripts/validate.py

##@ Documentation site

catalog-pins: ## Regenerate the plugin table and fail if README pins drift
	$(COMPOSE_RUN) --entrypoint python3 docs scripts/catalog_pins.py

docs-sync: catalog-pins ## Fetch pinned plugin READMEs and the docs-theme brand layer
	$(COMPOSE_RUN) --entrypoint python3 docs scripts/sync_sources.py

docs-sync-offline: catalog-pins ## Reuse the cached READMEs and brand files instead of fetching
	$(COMPOSE_RUN) --entrypoint python3 docs scripts/sync_sources.py --offline

# Which sync `docs-build` (and so `docs-check`) runs. Override it rather than
# running the sync by hand: `make docs-check DOCS_SYNC=docs-sync-offline`
# reuses the cache, where a bare `make docs-sync-offline` would be undone by
# the very next `docs-check`.
DOCS_SYNC ?= docs-sync

docs-build: $(DOCS_SYNC) ## Build the site to site/ (DOCS_SYNC=docs-sync-offline builds from the cache)
	$(COMPOSE_RUN) --entrypoint mkdocs docs build -d /docs/$(DOCS_BUILD)

docs-check: docs-build ## Build the site and assert the published output is complete (honours DOCS_SYNC)
	$(COMPOSE_RUN) --entrypoint python3 docs scripts/check_brand_paths.py
	$(COMPOSE_RUN) --entrypoint python3 docs scripts/check_site.py

docs-serve: ## Preview the site on http://127.0.0.1:8000
	$(COMPOSE) up docs

docs-clean: ## Remove the build output, fetched docs, fetched brand layer, and plugin cache
	@test -n "$(DOCS_BUILD)" || { echo "docs-clean: DOCS_BUILD must not be empty"; exit 1; }
	rm -rf "$(CURDIR)/$(DOCS_BUILD)" "$(CURDIR)/$(FETCHED)" "$(CURDIR)/.cache"
	rm -f $(THEME_FETCHED)
